//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""fcbb1451-7de6-4102-b686-3e58c5bf5247"",
            ""actions"": [
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""53760232-3450-4706-b955-d570710b39b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""aa9a0f14-9e59-4171-a2a2-5db4ddf8c499"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""313e91f6-3ce8-49ec-9f03-738ba07f19f3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""9af0cba2-4014-44ee-8ac0-a810b0421b45"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleMouse Camera"",
                    ""type"": ""Button"",
                    ""id"": ""ec2f4211-fa32-48f9-8d5d-27d4813e2a98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""GamepadAnalog"",
                    ""id"": ""025e98d3-287f-4643-b8f2-f4e87e6f97f6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2b2ca4e4-b94a-4d14-a515-4fb0ce12e309"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bb5c2941-6b8b-4077-8d70-652564b4791b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8f2bfa81-3247-4612-9ff7-0829978c6fb9"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""19fbb909-0e3c-4f98-a7a9-3f873eff227b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""KeyboardWASD"",
                    ""id"": ""0bc56efe-b149-4bc5-81c9-f6eacce7fff8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6d16b219-5fa3-4e40-853a-2b76de486649"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e354dc00-cf9e-4e16-a88b-132fbdf71a3c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e0ec8a10-ea07-44d6-8a37-d5c58716c101"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d60a39ed-a8bd-443b-83a4-53da6e156495"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""45e7fbd5-2df6-463e-8830-6c790fd03298"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b428a618-24a8-471e-971b-eaf676fd737d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98219a70-d2e9-4eaf-9d8a-b54477d3fe11"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db1ba311-52c1-4418-b94f-7faeda1d027a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""GamepadAnalog"",
                    ""id"": ""7cc66d14-b2e6-4acc-ba07-90cb32856f8a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a7f999df-d37b-43ef-8a3d-857e0d061118"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""211ec4a0-6bfb-49a2-9f34-488cb3847d7b"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dc49c98a-cecc-4826-8a6b-b58a98608d4f"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""56140e40-16df-4c31-bcf0-be1958e89675"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Mouse"",
                    ""id"": ""edec54f6-3a01-41ab-bb2b-07f57fc88829"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4a299131-084c-4979-9170-2c82ee656c7e"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f316681c-ce40-4498-ab14-27729fe840be"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5a739fcf-dd6c-48fc-a2b3-2a1a4d3513d0"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4417c15f-fe9a-40bb-a4f3-a92aba26dde0"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c0f05387-3e00-4841-876a-af31f38635f8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""ToggleMouse Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InRoadGame"",
            ""id"": ""a164f634-c049-49a4-a66d-fe848c0cb027"",
            ""actions"": [
                {
                    ""name"": ""Place"",
                    ""type"": ""Button"",
                    ""id"": ""1fa7f6b4-808e-45dc-86e5-3b1d8a4926e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Erase"",
                    ""type"": ""Button"",
                    ""id"": ""0c903b38-2ca2-4502-bf49-4c04e40d4b0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""3c34310c-0b21-438c-9c77-1c2bd52508e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Prev Piece"",
                    ""type"": ""Button"",
                    ""id"": ""d93e0422-331d-4e5b-9c65-64832283a3ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Next Piece"",
                    ""type"": ""Button"",
                    ""id"": ""040dcf0b-49fd-4af3-b7cc-8a329d24d78c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""2459dc2f-04b7-44f8-9f4a-d685dcd6f58c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Redo"",
                    ""type"": ""Button"",
                    ""id"": ""f2e7c9b3-1f54-4156-a7a4-97e689d284df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Play"",
                    ""type"": ""Button"",
                    ""id"": ""1998856c-ef92-480d-882a-f1ebd9d7f150"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Multiplier"",
                    ""type"": ""Button"",
                    ""id"": ""b22a84ae-4db5-47cb-ab87-4a040522393c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drawer"",
                    ""type"": ""Button"",
                    ""id"": ""6c2fe81e-31fb-45c6-b7ed-328dfb1757dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a22aa573-1be7-4c57-a23a-19811033fdc1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Place"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a92c8124-1142-405c-8e98-b98df54fc548"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Place"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c363395b-0cc8-40b4-b49c-f41913980c54"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Erase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24318bb3-b785-4e78-904f-b2a62e13612c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Erase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2fb9310-5871-4858-ae88-4a0ac4914388"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc5dad11-829a-4605-9d70-b93b1e760fa5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dea03ffa-7ce3-4818-9686-a44b6e36969c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Prev Piece"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""977594fc-c5c7-4b85-8c1b-355b5802032b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Prev Piece"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f7167da-883b-4eb7-9c50-c026f2bb73bf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Next Piece"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a463fef4-d7b8-4e44-b75a-0f2a0697c04b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Next Piece"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0202f1c-7f13-4f66-b071-f16350a35a09"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextPiece"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""576d5221-0e09-47e4-8624-63c8c8c3ca69"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a029b2d3-0cb1-4cb8-8c6f-6f9c7197cbdb"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""84c8ff6b-951b-4ee9-a46c-d219c216708b"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7bc8c89b-bd56-40e2-a194-005e58282bb3"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""eebb6144-2aed-4a92-bbaf-5ddcd8a6bd5c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""388f46bc-12b6-4c41-9434-a0420f4bb4dc"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""2348df0b-b150-4677-962f-466bb3f71a09"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2f516f57-5638-47c1-87a8-f351336ae14e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""014bdcd4-038e-4da5-8381-79e687fc65bf"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Play"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6e6b330-b667-47bd-bdb9-e0872e232984"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Play"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b6507e3-557e-4027-b8b5-0931b3d4c52f"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Multiplier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f05dd52-946e-42ea-8b2c-538277fc6cad"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Multiplier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63fe246b-dad7-4627-824b-46e63310b5ea"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drawer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1acb1fb6-d08f-4c26-bcef-95c0603ea245"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Drawer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InMiniGame"",
            ""id"": ""79e02167-d9b8-46e0-a869-e4e105a5fe88"",
            ""actions"": [
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""680ff207-d4ef-462a-88c4-6060e1f5377b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Check"",
                    ""type"": ""Button"",
                    ""id"": ""94a412bb-b09c-40e4-9756-584a4652e5af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""28dbd7f7-07dd-4d85-b261-89d02d51d456"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2056ba79-2946-4559-9f09-d28e73d34215"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa00bfcf-11bf-4af1-938f-30f9297899f8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Check"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c8475ba-82da-4171-a423-fa18eb55d35f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Check"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""In3DGame"",
            ""id"": ""e921d6a5-3af3-4ca9-ae7e-3b00ec02ba41"",
            ""actions"": [
                {
                    ""name"": ""Rotate Mode"",
                    ""type"": ""Button"",
                    ""id"": ""aa644b61-8a68-489d-a932-cf0af1fc0583"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Wheel"",
                    ""type"": ""Value"",
                    ""id"": ""fded7479-0b08-4259-9938-db011f76c0ed"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Right Click"",
                    ""type"": ""Button"",
                    ""id"": ""80d6f682-fd24-472f-935c-567721a94648"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Look"",
                    ""type"": ""Value"",
                    ""id"": ""a3a5fcc0-5be2-4ef4-beca-de8ad99df9ac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Left Click"",
                    ""type"": ""Button"",
                    ""id"": ""1555beac-798d-4282-b963-5d5912974a26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Separate Mode"",
                    ""type"": ""Button"",
                    ""id"": ""b51adc25-4010-4e37-ad2a-117660b18392"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""b183b550-7eaf-44b4-966d-abc4a4b6a04c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fcf7027d-b7b7-4d73-befa-a1f58e101429"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Rotate Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""168427ce-fcbc-4e2e-9dd1-43b1f5603fd3"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamepadControls"",
                    ""action"": ""Rotate Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c687c56-8628-47c9-9827-7e9d1de9f75d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Separate Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ced1757b-3006-4e2c-8323-b35436771e76"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Separate Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4171202c-7760-4fc1-9fc2-4a232ea719e8"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""078d28b6-239f-47ee-876d-92e88b2e8887"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77363e8e-5088-4d25-bef8-984849671b2d"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""520eb9fd-021a-4642-bfd4-4561c4961299"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Left Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a66666ca-adb7-41e0-a707-a829383810da"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd6c217b-0df0-4907-97c4-03a5a851f729"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Mouse Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c946087f-4c17-48a0-8c3d-4a9378e5e4dc"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Right Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2aaaba8a-d9f8-4c96-a1a5-d27701ab00b3"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouseControls"",
                    ""action"": ""Mouse Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""GamepadControls"",
            ""bindingGroup"": ""GamepadControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""KeyboardMouseControls"",
            ""bindingGroup"": ""KeyboardMouseControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_Back = m_InGame.FindAction("Back", throwIfNotFound: true);
        m_InGame_Select = m_InGame.FindAction("Select", throwIfNotFound: true);
        m_InGame_Move = m_InGame.FindAction("Move", throwIfNotFound: true);
        m_InGame_MoveCamera = m_InGame.FindAction("MoveCamera", throwIfNotFound: true);
        m_InGame_ToggleMouseCamera = m_InGame.FindAction("ToggleMouse Camera", throwIfNotFound: true);
        // InRoadGame
        m_InRoadGame = asset.FindActionMap("InRoadGame", throwIfNotFound: true);
        m_InRoadGame_Place = m_InRoadGame.FindAction("Place", throwIfNotFound: true);
        m_InRoadGame_Erase = m_InRoadGame.FindAction("Erase", throwIfNotFound: true);
        m_InRoadGame_Rotate = m_InRoadGame.FindAction("Rotate", throwIfNotFound: true);
        m_InRoadGame_PrevPiece = m_InRoadGame.FindAction("Prev Piece", throwIfNotFound: true);
        m_InRoadGame_NextPiece = m_InRoadGame.FindAction("Next Piece", throwIfNotFound: true);
        m_InRoadGame_Undo = m_InRoadGame.FindAction("Undo", throwIfNotFound: true);
        m_InRoadGame_Redo = m_InRoadGame.FindAction("Redo", throwIfNotFound: true);
        m_InRoadGame_Play = m_InRoadGame.FindAction("Play", throwIfNotFound: true);
        m_InRoadGame_Multiplier = m_InRoadGame.FindAction("Multiplier", throwIfNotFound: true);
        m_InRoadGame_Drawer = m_InRoadGame.FindAction("Drawer", throwIfNotFound: true);
        // InMiniGame
        m_InMiniGame = asset.FindActionMap("InMiniGame", throwIfNotFound: true);
        m_InMiniGame_Rotate = m_InMiniGame.FindAction("Rotate", throwIfNotFound: true);
        m_InMiniGame_Check = m_InMiniGame.FindAction("Check", throwIfNotFound: true);
        // In3DGame
        m_In3DGame = asset.FindActionMap("In3DGame", throwIfNotFound: true);
        m_In3DGame_RotateMode = m_In3DGame.FindAction("Rotate Mode", throwIfNotFound: true);
        m_In3DGame_MouseWheel = m_In3DGame.FindAction("Mouse Wheel", throwIfNotFound: true);
        m_In3DGame_RightClick = m_In3DGame.FindAction("Right Click", throwIfNotFound: true);
        m_In3DGame_MouseLook = m_In3DGame.FindAction("Mouse Look", throwIfNotFound: true);
        m_In3DGame_LeftClick = m_In3DGame.FindAction("Left Click", throwIfNotFound: true);
        m_In3DGame_SeparateMode = m_In3DGame.FindAction("Separate Mode", throwIfNotFound: true);
        m_In3DGame_Delete = m_In3DGame.FindAction("Delete", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_Back;
    private readonly InputAction m_InGame_Select;
    private readonly InputAction m_InGame_Move;
    private readonly InputAction m_InGame_MoveCamera;
    private readonly InputAction m_InGame_ToggleMouseCamera;
    public struct InGameActions
    {
        private @Controls m_Wrapper;
        public InGameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Back => m_Wrapper.m_InGame_Back;
        public InputAction @Select => m_Wrapper.m_InGame_Select;
        public InputAction @Move => m_Wrapper.m_InGame_Move;
        public InputAction @MoveCamera => m_Wrapper.m_InGame_MoveCamera;
        public InputAction @ToggleMouseCamera => m_Wrapper.m_InGame_ToggleMouseCamera;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @MoveCamera.started += instance.OnMoveCamera;
            @MoveCamera.performed += instance.OnMoveCamera;
            @MoveCamera.canceled += instance.OnMoveCamera;
            @ToggleMouseCamera.started += instance.OnToggleMouseCamera;
            @ToggleMouseCamera.performed += instance.OnToggleMouseCamera;
            @ToggleMouseCamera.canceled += instance.OnToggleMouseCamera;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @MoveCamera.started -= instance.OnMoveCamera;
            @MoveCamera.performed -= instance.OnMoveCamera;
            @MoveCamera.canceled -= instance.OnMoveCamera;
            @ToggleMouseCamera.started -= instance.OnToggleMouseCamera;
            @ToggleMouseCamera.performed -= instance.OnToggleMouseCamera;
            @ToggleMouseCamera.canceled -= instance.OnToggleMouseCamera;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);

    // InRoadGame
    private readonly InputActionMap m_InRoadGame;
    private List<IInRoadGameActions> m_InRoadGameActionsCallbackInterfaces = new List<IInRoadGameActions>();
    private readonly InputAction m_InRoadGame_Place;
    private readonly InputAction m_InRoadGame_Erase;
    private readonly InputAction m_InRoadGame_Rotate;
    private readonly InputAction m_InRoadGame_PrevPiece;
    private readonly InputAction m_InRoadGame_NextPiece;
    private readonly InputAction m_InRoadGame_Undo;
    private readonly InputAction m_InRoadGame_Redo;
    private readonly InputAction m_InRoadGame_Play;
    private readonly InputAction m_InRoadGame_Multiplier;
    private readonly InputAction m_InRoadGame_Drawer;
    public struct InRoadGameActions
    {
        private @Controls m_Wrapper;
        public InRoadGameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Place => m_Wrapper.m_InRoadGame_Place;
        public InputAction @Erase => m_Wrapper.m_InRoadGame_Erase;
        public InputAction @Rotate => m_Wrapper.m_InRoadGame_Rotate;
        public InputAction @PrevPiece => m_Wrapper.m_InRoadGame_PrevPiece;
        public InputAction @NextPiece => m_Wrapper.m_InRoadGame_NextPiece;
        public InputAction @Undo => m_Wrapper.m_InRoadGame_Undo;
        public InputAction @Redo => m_Wrapper.m_InRoadGame_Redo;
        public InputAction @Play => m_Wrapper.m_InRoadGame_Play;
        public InputAction @Multiplier => m_Wrapper.m_InRoadGame_Multiplier;
        public InputAction @Drawer => m_Wrapper.m_InRoadGame_Drawer;
        public InputActionMap Get() { return m_Wrapper.m_InRoadGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InRoadGameActions set) { return set.Get(); }
        public void AddCallbacks(IInRoadGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InRoadGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InRoadGameActionsCallbackInterfaces.Add(instance);
            @Place.started += instance.OnPlace;
            @Place.performed += instance.OnPlace;
            @Place.canceled += instance.OnPlace;
            @Erase.started += instance.OnErase;
            @Erase.performed += instance.OnErase;
            @Erase.canceled += instance.OnErase;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @PrevPiece.started += instance.OnPrevPiece;
            @PrevPiece.performed += instance.OnPrevPiece;
            @PrevPiece.canceled += instance.OnPrevPiece;
            @NextPiece.started += instance.OnNextPiece;
            @NextPiece.performed += instance.OnNextPiece;
            @NextPiece.canceled += instance.OnNextPiece;
            @Undo.started += instance.OnUndo;
            @Undo.performed += instance.OnUndo;
            @Undo.canceled += instance.OnUndo;
            @Redo.started += instance.OnRedo;
            @Redo.performed += instance.OnRedo;
            @Redo.canceled += instance.OnRedo;
            @Play.started += instance.OnPlay;
            @Play.performed += instance.OnPlay;
            @Play.canceled += instance.OnPlay;
            @Multiplier.started += instance.OnMultiplier;
            @Multiplier.performed += instance.OnMultiplier;
            @Multiplier.canceled += instance.OnMultiplier;
            @Drawer.started += instance.OnDrawer;
            @Drawer.performed += instance.OnDrawer;
            @Drawer.canceled += instance.OnDrawer;
        }

        private void UnregisterCallbacks(IInRoadGameActions instance)
        {
            @Place.started -= instance.OnPlace;
            @Place.performed -= instance.OnPlace;
            @Place.canceled -= instance.OnPlace;
            @Erase.started -= instance.OnErase;
            @Erase.performed -= instance.OnErase;
            @Erase.canceled -= instance.OnErase;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @PrevPiece.started -= instance.OnPrevPiece;
            @PrevPiece.performed -= instance.OnPrevPiece;
            @PrevPiece.canceled -= instance.OnPrevPiece;
            @NextPiece.started -= instance.OnNextPiece;
            @NextPiece.performed -= instance.OnNextPiece;
            @NextPiece.canceled -= instance.OnNextPiece;
            @Undo.started -= instance.OnUndo;
            @Undo.performed -= instance.OnUndo;
            @Undo.canceled -= instance.OnUndo;
            @Redo.started -= instance.OnRedo;
            @Redo.performed -= instance.OnRedo;
            @Redo.canceled -= instance.OnRedo;
            @Play.started -= instance.OnPlay;
            @Play.performed -= instance.OnPlay;
            @Play.canceled -= instance.OnPlay;
            @Multiplier.started -= instance.OnMultiplier;
            @Multiplier.performed -= instance.OnMultiplier;
            @Multiplier.canceled -= instance.OnMultiplier;
            @Drawer.started -= instance.OnDrawer;
            @Drawer.performed -= instance.OnDrawer;
            @Drawer.canceled -= instance.OnDrawer;
        }

        public void RemoveCallbacks(IInRoadGameActions instance)
        {
            if (m_Wrapper.m_InRoadGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInRoadGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InRoadGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InRoadGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InRoadGameActions @InRoadGame => new InRoadGameActions(this);

    // InMiniGame
    private readonly InputActionMap m_InMiniGame;
    private List<IInMiniGameActions> m_InMiniGameActionsCallbackInterfaces = new List<IInMiniGameActions>();
    private readonly InputAction m_InMiniGame_Rotate;
    private readonly InputAction m_InMiniGame_Check;
    public struct InMiniGameActions
    {
        private @Controls m_Wrapper;
        public InMiniGameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Rotate => m_Wrapper.m_InMiniGame_Rotate;
        public InputAction @Check => m_Wrapper.m_InMiniGame_Check;
        public InputActionMap Get() { return m_Wrapper.m_InMiniGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InMiniGameActions set) { return set.Get(); }
        public void AddCallbacks(IInMiniGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InMiniGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InMiniGameActionsCallbackInterfaces.Add(instance);
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Check.started += instance.OnCheck;
            @Check.performed += instance.OnCheck;
            @Check.canceled += instance.OnCheck;
        }

        private void UnregisterCallbacks(IInMiniGameActions instance)
        {
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Check.started -= instance.OnCheck;
            @Check.performed -= instance.OnCheck;
            @Check.canceled -= instance.OnCheck;
        }

        public void RemoveCallbacks(IInMiniGameActions instance)
        {
            if (m_Wrapper.m_InMiniGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInMiniGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InMiniGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InMiniGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InMiniGameActions @InMiniGame => new InMiniGameActions(this);

    // In3DGame
    private readonly InputActionMap m_In3DGame;
    private List<IIn3DGameActions> m_In3DGameActionsCallbackInterfaces = new List<IIn3DGameActions>();
    private readonly InputAction m_In3DGame_RotateMode;
    private readonly InputAction m_In3DGame_MouseWheel;
    private readonly InputAction m_In3DGame_RightClick;
    private readonly InputAction m_In3DGame_MouseLook;
    private readonly InputAction m_In3DGame_LeftClick;
    private readonly InputAction m_In3DGame_SeparateMode;
    private readonly InputAction m_In3DGame_Delete;
    public struct In3DGameActions
    {
        private @Controls m_Wrapper;
        public In3DGameActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @RotateMode => m_Wrapper.m_In3DGame_RotateMode;
        public InputAction @MouseWheel => m_Wrapper.m_In3DGame_MouseWheel;
        public InputAction @RightClick => m_Wrapper.m_In3DGame_RightClick;
        public InputAction @MouseLook => m_Wrapper.m_In3DGame_MouseLook;
        public InputAction @LeftClick => m_Wrapper.m_In3DGame_LeftClick;
        public InputAction @SeparateMode => m_Wrapper.m_In3DGame_SeparateMode;
        public InputAction @Delete => m_Wrapper.m_In3DGame_Delete;
        public InputActionMap Get() { return m_Wrapper.m_In3DGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(In3DGameActions set) { return set.Get(); }
        public void AddCallbacks(IIn3DGameActions instance)
        {
            if (instance == null || m_Wrapper.m_In3DGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_In3DGameActionsCallbackInterfaces.Add(instance);
            @RotateMode.started += instance.OnRotateMode;
            @RotateMode.performed += instance.OnRotateMode;
            @RotateMode.canceled += instance.OnRotateMode;
            @MouseWheel.started += instance.OnMouseWheel;
            @MouseWheel.performed += instance.OnMouseWheel;
            @MouseWheel.canceled += instance.OnMouseWheel;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
            @MouseLook.started += instance.OnMouseLook;
            @MouseLook.performed += instance.OnMouseLook;
            @MouseLook.canceled += instance.OnMouseLook;
            @LeftClick.started += instance.OnLeftClick;
            @LeftClick.performed += instance.OnLeftClick;
            @LeftClick.canceled += instance.OnLeftClick;
            @SeparateMode.started += instance.OnSeparateMode;
            @SeparateMode.performed += instance.OnSeparateMode;
            @SeparateMode.canceled += instance.OnSeparateMode;
            @Delete.started += instance.OnDelete;
            @Delete.performed += instance.OnDelete;
            @Delete.canceled += instance.OnDelete;
        }

        private void UnregisterCallbacks(IIn3DGameActions instance)
        {
            @RotateMode.started -= instance.OnRotateMode;
            @RotateMode.performed -= instance.OnRotateMode;
            @RotateMode.canceled -= instance.OnRotateMode;
            @MouseWheel.started -= instance.OnMouseWheel;
            @MouseWheel.performed -= instance.OnMouseWheel;
            @MouseWheel.canceled -= instance.OnMouseWheel;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
            @MouseLook.started -= instance.OnMouseLook;
            @MouseLook.performed -= instance.OnMouseLook;
            @MouseLook.canceled -= instance.OnMouseLook;
            @LeftClick.started -= instance.OnLeftClick;
            @LeftClick.performed -= instance.OnLeftClick;
            @LeftClick.canceled -= instance.OnLeftClick;
            @SeparateMode.started -= instance.OnSeparateMode;
            @SeparateMode.performed -= instance.OnSeparateMode;
            @SeparateMode.canceled -= instance.OnSeparateMode;
            @Delete.started -= instance.OnDelete;
            @Delete.performed -= instance.OnDelete;
            @Delete.canceled -= instance.OnDelete;
        }

        public void RemoveCallbacks(IIn3DGameActions instance)
        {
            if (m_Wrapper.m_In3DGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IIn3DGameActions instance)
        {
            foreach (var item in m_Wrapper.m_In3DGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_In3DGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public In3DGameActions @In3DGame => new In3DGameActions(this);
    private int m_GamepadControlsSchemeIndex = -1;
    public InputControlScheme GamepadControlsScheme
    {
        get
        {
            if (m_GamepadControlsSchemeIndex == -1) m_GamepadControlsSchemeIndex = asset.FindControlSchemeIndex("GamepadControls");
            return asset.controlSchemes[m_GamepadControlsSchemeIndex];
        }
    }
    private int m_KeyboardMouseControlsSchemeIndex = -1;
    public InputControlScheme KeyboardMouseControlsScheme
    {
        get
        {
            if (m_KeyboardMouseControlsSchemeIndex == -1) m_KeyboardMouseControlsSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouseControls");
            return asset.controlSchemes[m_KeyboardMouseControlsSchemeIndex];
        }
    }
    public interface IInGameActions
    {
        void OnBack(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnToggleMouseCamera(InputAction.CallbackContext context);
    }
    public interface IInRoadGameActions
    {
        void OnPlace(InputAction.CallbackContext context);
        void OnErase(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnPrevPiece(InputAction.CallbackContext context);
        void OnNextPiece(InputAction.CallbackContext context);
        void OnUndo(InputAction.CallbackContext context);
        void OnRedo(InputAction.CallbackContext context);
        void OnPlay(InputAction.CallbackContext context);
        void OnMultiplier(InputAction.CallbackContext context);
        void OnDrawer(InputAction.CallbackContext context);
    }
    public interface IInMiniGameActions
    {
        void OnRotate(InputAction.CallbackContext context);
        void OnCheck(InputAction.CallbackContext context);
    }
    public interface IIn3DGameActions
    {
        void OnRotateMode(InputAction.CallbackContext context);
        void OnMouseWheel(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnMouseLook(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnSeparateMode(InputAction.CallbackContext context);
        void OnDelete(InputAction.CallbackContext context);
    }
}
